import streamlit as st
R = {
    "K": [["S", "P"], ["P1", "O"], ["P1", "Pel"], ["P1", "Ket"], ["P1", "P2"], ["P1", "P3"], ["P1", "P4"]],

    "P1": [["S", "P"]],
    "P2": [["O", "Pel"]],
    "P3": [["O", "Ket"]],
    "P4": [["P2", "Ket"]],

    "S": [["Gagas"], ["Alaya"], ["Dr. Siti Rahayu"], ["Ani"], ["Adi Santoso"], ["Bu Ratna"], ["Prof. Dr. Hadi Prayitno"], ["Kiki"], ["Ibu Sinta"], ["Bapak Haryono"], 
          ["dia"], ["saya"], ["kita"], 
          ["nenek"], ["orang"], ["mahasiswa"], ["orang dewasa saja"], ["pemadam kebakaran"], ["anak laki-laki"], ["ibu"], ["siswa"], ["polisi"], ["burung"], ["ikan koi"], ["kuda pacuan"], ["monyet kecil"], ["kelinci putih"], ["lumba-lumba itu"], ["kupu-kupu"], ["sapi"], ["lebah"], ["buaya"], ["mahasiswa"], ["laut mediterania"], ["bukit tinggi"], ["danau baikal"], ["pantai copacabana"], ["bali"], ["kota bandung"], ["bogor"], ["monas"], ["denpasar"], ["surabaya"], ["pentas ogoh-ogoh"], ["arab saudi"], ["sepatu"], ["rumah"], ["kucing"], ["pengunjung"], ["siswa"], ["kamar tidur"], ["pertunjukan teater"], ["mobil"], ["bunga"], ["kotak besar"], ["kuda hitam"], ["bapak"], ["teman saya"], ["asrama putri"], ["bapak guru"], ["kakek"], ["pelatih tari"], ["rencana pelajaran"], ["pengembangan teknologi"], ["gadis kecil"], ["air terjun"], ["pertunjukan seni"], ["rumah tua"], ["bunga yang mekar"], ["kucing hitam"], ["udara sejuk"], ["prestasi anak-anak"], ["rasa cokelat"], ["pohon rindang"], ["air hujan"], ["cita-cita tinggi"], ["pameran"], ["budaya lokal"], ["hewan peliharaan"] ,["daun ubi"], ["sedikit waktu untuk"], ["ketertiban"], ["kebun"], ["acara"], ["kegiatan pengabdian"], ["wahana"], ["penduduk desa"], ["taman kota"], ["makanan lezat"], ["perpustakaan kampus"], ["jalan"], ["siang hari"], ["kolam taman"], ["lintasan pacu"], ["ranting pohon"], ["kebun"], ["laut lepas"], ["padang rumput"], ["rumput"], ["nektar"], ["tepi danau"], ["acara seminar itu"], ["universitas"], ["kuliah"], ["pantai"], ["pemimpin proyek"], ["warung kopi"], ["pakar bidang ekologi"], ["lomba menyanyi"], ["pembicara"], ["seminar"], ["tetangga"], ["pantainya"], ["pemandangan alam"], ["danau terdalam"], ["dunia"], ["ikon kota rio de janeiro"], ["kulinernya"], ["kota hujan"], ["tengah jakarta"], ["budaya indah"], ["malam hari"], ["jawa timur"], ["tahun baru saka"], ["negara penghasil minyak"], ["di dunia"], ["negara kepulauan"], ["rak sepatu"], ["tahap kontruksi"], ["taman belakang rumah"], ["perpustakaan"], ["acara tersebut"], ["setiap pagi"], ["mainan anak-anak"], ["buku"], ["rokok"], ["sejarah kebudayaan bali"], ["bahasa jepang"], ["pemain sepak bola"], ["orang medan"], ["kursi rotan"], ["dua orang"], ["boneka barunya"], ["sejarah panjang"], ["taman kita"], ["anak-anak"], ["pikiran"], ["orang tua"], ["kelemahannya"], ["kesejukan"], ["suasana romantis"], ["pendorong kesuksesan"], ["peliharaan manis"], ["karya seni kontemporer"], ["wisata daerah itu"], ["keluarga kami"], ["digunakan"], 
          ["NP", "Prep"], ["NumP", "NP"], ["NP", "Pronoun"], ["NP", "NumP"]],

    "P" : [["Adj", "Verb"], ["VP", "Verb"], 
           ["mengambil"], ["menghadiri"], ["mengikuti"], ["diperbolehkan"], ["menaiki"], ["mempunyai"], ["menyelamatkan"], ["bermain"], ["memasak"], ["belajar"], ["menjaga"], ["terbang"], ["berenang"], ["berlari"], ["bergelantungan"], ["melompat-lompat"], ["hinggap"], ["mengunyah"], ["mengumpulkan"], ["sedang"], ["berjemur"], ["hadir"], ["memberikan"], ["adalah"], ["merupakan"], ["menjadi"], ["akan"], ["membantu"], ["terkenal dengan"], ["dikenal dengan"], ["terletak"], ["memiliki"], ["merupakan"], ["terpajang"], ["dalam tahap kontruksi"], ["belajar"], ["hadir"], ["nyaman"], ["indah"], ["sudah"], ["disiram"], ["berisi"], ["berlari"], ["membeli"], ["meneliti"], ["kursus"], ["orang medan"], ["menyukai"], ["dua orang"], ["disusun"], ["berlangsung"], ["senang"], ["indah"], ["menghibur"], ["membuat"], ["hewan peliharaan manis"], ["menampilkan"]],


    "O" :  [["Gagas"], ["Alaya"], ["Dr. Siti Rahayu"], ["Ani"], ["Adi Santoso"], ["Bu Ratna"], ["Prof. Dr. Hadi Prayitno"], ["Kiki"], ["Ibu Sinta"], ["Bapak Haryono"],
            ["dia"], ["saya"], ["kita"], 
            ["nenek"], ["orang"], ["mahasiswa"], ["orang dewasa saja"], ["pemadam kebakaran"], ["anak laki-laki"], ["ibu"], ["siswa"], ["polisi"], ["burung"], ["ikan koi"], ["kuda pacuan"], ["monyet kecil"], ["kelinci putih"], ["lumba-lumba itu"], ["kupu-kupu"], ["sapi"], ["lebah"], ["buaya"], ["mahasiswa"], ["laut mediterania"], ["bukit tinggi"], ["danau baikal"], ["pantai copacabana"], ["bali"], ["kota bandung"], ["bogor"], ["monas"], ["denpasar"], ["surabaya"], ["pentas ogoh-ogoh"], ["arab saudi"], ["sepatu"], ["rumah"], ["kucing"], ["pengunjung"], ["siswa"], ["kamar tidur"], ["pertunjukan teater"], ["mobil"], ["bunga"], ["kotak besar"], ["kuda hitam"], ["bapak"], ["teman saya"], ["asrama putri"], ["bapak guru"], ["kakek"], ["pelatih tari"], ["rencana pelajaran"], ["pengembangan teknologi"], ["gadis kecil"], ["air terjun"], ["pertunjukan seni"], ["rumah tua"], ["bunga yang mekar"], ["kucing hitam"], ["udara sejuk"], ["prestasi anak-anak"], ["rasa cokelat"], ["pohon rindang"], ["air hujan"], ["cita-cita tinggi"], ["pameran"], ["budaya lokal"], ["hewan peliharaan"] ,["daun ubi"], ["sedikit waktu untuk"], ["ketertiban"], ["kebun"], ["acara"], ["kegiatan pengabdian"], ["wahana"], ["penduduk desa"], ["taman kota"], ["makanan lezat"], ["perpustakaan kampus"], ["jalan"], ["siang hari"], ["kolam taman"], ["lintasan pacu"], ["ranting pohon"], ["kebun"], ["laut lepas"], ["padang rumput"], ["rumput"], ["nektar"], ["tepi danau"], ["acara seminar itu"], ["universitas"], ["kuliah"], ["pantai"], ["pemimpin proyek"], ["warung kopi"], ["pakar bidang ekologi"], ["lomba menyanyi"], ["pembicara"], ["seminar"], ["tetangga"], ["pantainya"], ["pemandangan alam"], ["danau terdalam"], ["dunia"], ["ikon kota rio de janeiro"], ["kulinernya"], ["kota hujan"], ["tengah jakarta"], ["budaya indah"], ["malam hari"], ["jawa timur"], ["tahun baru saka"], ["negara penghasil minyak"], ["di dunia"], ["negara kepulauan"], ["rak sepatu"], ["tahap kontruksi"], ["taman belakang rumah"], ["perpustakaan"], ["acara tersebut"], ["setiap pagi"], ["mainan anak-anak"], ["buku"], ["rokok"], ["sejarah kebudayaan bali"], ["bahasa jepang"], ["pemain sepak bola"], ["orang medan"], ["kursi rotan"], ["dua orang"], ["boneka barunya"], ["sejarah panjang"], ["taman kita"], ["anak-anak"], ["pikiran"], ["orang tua"], ["kelemahannya"], ["kesejukan"], ["suasana romantis"], ["pendorong kesuksesan"], ["peliharaan manis"], ["karya seni kontemporer"], ["wisata daerah itu"], ["keluarga kami"], ["digunakan"],
            ["NP", "Prep"], ["NumP" "NP"], ["NP", "Pronoun"], ["NP", "NumP"]],

    "Ket" :  [["Gagas"], ["Alaya"], ["Dr. Siti Rahayu"], ["Ani"], ["Adi Santoso"], ["Bu Ratna"], ["Prof. Dr. Hadi Prayitno"], ["Kiki"], ["Ibu Sinta"], ["Bapak Haryono"],
              ["dia"], ["saya"], ["kita"], 
              ["nenek"], ["orang"], ["mahasiswa"], ["orang dewasa saja"], ["pemadam kebakaran"], ["anak laki-laki"], ["ibu"], ["siswa"], ["polisi"], ["burung"], ["ikan koi"], ["kuda pacuan"], ["monyet kecil"], ["kelinci putih"], ["lumba-lumba itu"], ["kupu-kupu"], ["sapi"], ["lebah"], ["buaya"], ["mahasiswa"], ["laut mediterania"], ["bukit tinggi"], ["danau baikal"], ["pantai copacabana"], ["bali"], ["kota bandung"], ["bogor"], ["monas"], ["denpasar"], ["surabaya"], ["pentas ogoh-ogoh"], ["arab saudi"], ["sepatu"], ["rumah"], ["kucing"], ["pengunjung"], ["siswa"], ["kamar tidur"], ["pertunjukan teater"], ["mobil"], ["bunga"], ["kotak besar"], ["kuda hitam"], ["bapak"], ["teman saya"], ["asrama putri"], ["bapak guru"], ["kakek"], ["pelatih tari"], ["rencana pelajaran"], ["pengembangan teknologi"], ["gadis kecil"], ["air terjun"], ["pertunjukan seni"], ["rumah tua"], ["bunga yang mekar"], ["kucing hitam"], ["udara sejuk"], ["prestasi anak-anak"], ["rasa cokelat"], ["pohon rindang"], ["air hujan"], ["cita-cita tinggi"], ["pameran"], ["budaya lokal"], ["hewan peliharaan"] ,["daun ubi"], ["sedikit waktu untuk"], ["ketertiban"], ["kebun"], ["acara"], ["kegiatan pengabdian"], ["wahana"], ["penduduk desa"], ["taman kota"], ["makanan lezat"], ["perpustakaan kampus"], ["jalan"], ["siang hari"], ["kolam taman"], ["lintasan pacu"], ["ranting pohon"], ["kebun"], ["laut lepas"], ["padang rumput"], ["rumput"], ["nektar"], ["tepi danau"], ["acara seminar itu"], ["universitas"], ["kuliah"], ["pantai"], ["pemimpin proyek"], ["warung kopi"], ["pakar bidang ekologi"], ["lomba menyanyi"], ["pembicara"], ["seminar"], ["tetangga"], ["pantainya"], ["pemandangan alam"], ["danau terdalam"], ["dunia"], ["ikon kota rio de janeiro"], ["kulinernya"], ["kota hujan"], ["tengah jakarta"], ["budaya indah"], ["malam hari"], ["jawa timur"], ["tahun baru saka"], ["negara penghasil minyak"], ["di dunia"], ["negara kepulauan"], ["rak sepatu"], ["tahap kontruksi"], ["taman belakang rumah"], ["perpustakaan"], ["acara tersebut"], ["setiap pagi"], ["mainan anak-anak"], ["buku"], ["rokok"], ["sejarah kebudayaan bali"], ["bahasa jepang"], ["pemain sepak bola"], ["orang medan"], ["kursi rotan"], ["dua orang"], ["boneka barunya"], ["sejarah panjang"], ["taman kita"], ["anak-anak"], ["pikiran"], ["orang tua"], ["kelemahannya"], ["kesejukan"], ["suasana romantis"], ["pendorong kesuksesan"], ["peliharaan manis"], ["karya seni kontemporer"], ["wisata daerah itu"], ["keluarga kami"], ["digunakan"],
              ["NP", "Prep"], ["NumP" "NP"], ["NP", "Pronoun"], ["NP", "NumP"],
              
              ["Prep", "NP"], ["Prep", "VP"], ["Prep", "PP"], ["AdjP", "NP"], ["Adv", "NP"]],

    "Pel" :  [["Gagas"], ["Alaya"], ["Dr. Siti Rahayu"], ["Ani"], ["Adi Santoso"], ["Bu Ratna"], ["Prof. Dr. Hadi Prayitno"], ["Kiki"], ["Ibu Sinta"], ["Bapak Haryono"],
              ["dia"], ["saya"], ["kita"], 
              ["nenek"], ["orang"], ["mahasiswa"], ["orang dewasa saja"], ["pemadam kebakaran"], ["anak laki-laki"], ["ibu"], ["siswa"], ["polisi"], ["burung"], ["ikan koi"], ["kuda pacuan"], ["monyet kecil"], ["kelinci putih"], ["lumba-lumba itu"], ["kupu-kupu"], ["sapi"], ["lebah"], ["buaya"], ["mahasiswa"], ["laut mediterania"], ["bukit tinggi"], ["danau baikal"], ["pantai copacabana"], ["bali"], ["kota bandung"], ["bogor"], ["monas"], ["denpasar"], ["surabaya"], ["pentas ogoh-ogoh"], ["arab saudi"], ["sepatu"], ["rumah"], ["kucing"], ["pengunjung"], ["siswa"], ["kamar tidur"], ["pertunjukan teater"], ["mobil"], ["bunga"], ["kotak besar"], ["kuda hitam"], ["bapak"], ["teman saya"], ["asrama putri"], ["bapak guru"], ["kakek"], ["pelatih tari"], ["rencana pelajaran"], ["pengembangan teknologi"], ["gadis kecil"], ["air terjun"], ["pertunjukan seni"], ["rumah tua"], ["bunga yang mekar"], ["kucing hitam"], ["udara sejuk"], ["prestasi anak-anak"], ["rasa cokelat"], ["pohon rindang"], ["air hujan"], ["cita-cita tinggi"], ["pameran"], ["budaya lokal"], ["hewan peliharaan"] ,["daun ubi"], ["sedikit waktu untuk"], ["ketertiban"], ["kebun"], ["acara"], ["kegiatan pengabdian"], ["wahana"], ["penduduk desa"], ["taman kota"], ["makanan lezat"], ["perpustakaan kampus"], ["jalan"], ["siang hari"], ["kolam taman"], ["lintasan pacu"], ["ranting pohon"], ["kebun"], ["laut lepas"], ["padang rumput"], ["rumput"], ["nektar"], ["tepi danau"], ["acara seminar itu"], ["universitas"], ["kuliah"], ["pantai"], ["pemimpin proyek"], ["warung kopi"], ["pakar bidang ekologi"], ["lomba menyanyi"], ["pembicara"], ["seminar"], ["tetangga"], ["pantainya"], ["pemandangan alam"], ["danau terdalam"], ["dunia"], ["ikon kota rio de janeiro"], ["kulinernya"], ["kota hujan"], ["tengah jakarta"], ["budaya indah"], ["malam hari"], ["jawa timur"], ["tahun baru saka"], ["negara penghasil minyak"], ["di dunia"], ["negara kepulauan"], ["rak sepatu"], ["tahap kontruksi"], ["taman belakang rumah"], ["perpustakaan"], ["acara tersebut"], ["setiap pagi"], ["mainan anak-anak"], ["buku"], ["rokok"], ["sejarah kebudayaan bali"], ["bahasa jepang"], ["pemain sepak bola"], ["orang medan"], ["kursi rotan"], ["dua orang"], ["boneka barunya"], ["sejarah panjang"], ["taman kita"], ["anak-anak"], ["pikiran"], ["orang tua"], ["kelemahannya"], ["kesejukan"], ["suasana romantis"], ["pendorong kesuksesan"], ["peliharaan manis"], ["karya seni kontemporer"], ["wisata daerah itu"], ["keluarga kami"], ["digunakan"],
              ["NP", "Prep"], ["NumP" "NP"], ["NP", "Pronoun"], ["NP", "NumP"],
              ["AdjP", "NP"], ["NumP", "NP"]],

    "NP" : [["Gagas"], ["Alaya"], ["Dr. Siti Rahayu"], ["Ani"], ["Adi Santoso"], ["Bu Ratna"], ["Prof. Dr. Hadi Prayitno"], ["Kiki"], ["Ibu Sinta"], ["Bapak Haryono"], 
          ["dia"], ["saya"], ["kita"], 
          ["nenek"], ["orang"], ["mahasiswa"], ["orang dewasa saja"], ["pemadam kebakaran"], ["anak laki-laki"], ["ibu"], ["siswa"], ["polisi"], ["burung"], ["ikan koi"], ["kuda pacuan"], ["monyet kecil"], ["kelinci putih"], ["lumba-lumba itu"], ["kupu-kupu"], ["sapi"], ["lebah"], ["buaya"], ["mahasiswa"], ["laut mediterania"], ["bukit tinggi"], ["danau baikal"], ["pantai copacabana"], ["bali"], ["kota bandung"], ["bogor"], ["monas"], ["denpasar"], ["surabaya"], ["pentas ogoh-ogoh"], ["arab saudi"], ["sepatu"], ["rumah"], ["kucing"], ["pengunjung"], ["siswa"], ["kamar tidur"], ["pertunjukan teater"], ["mobil"], ["bunga"], ["kotak besar"], ["kuda hitam"], ["bapak"], ["teman saya"], ["asrama putri"], ["bapak guru"], ["kakek"], ["pelatih tari"], ["rencana pelajaran"], ["pengembangan teknologi"], ["gadis kecil"], ["air terjun"], ["pertunjukan seni"], ["rumah tua"], ["bunga yang mekar"], ["kucing hitam"], ["udara sejuk"], ["prestasi anak-anak"], ["rasa cokelat"], ["pohon rindang"], ["air hujan"], ["cita-cita tinggi"], ["pameran"], ["budaya lokal"], ["hewan peliharaan"] ,["daun ubi"], ["sedikit waktu untuk"], ["ketertiban"], ["kebun"], ["acara"], ["kegiatan pengabdian"], ["wahana"], ["penduduk desa"], ["taman kota"], ["makanan lezat"], ["perpustakaan kampus"], ["jalan"], ["siang hari"], ["kolam taman"], ["lintasan pacu"], ["ranting pohon"], ["kebun"], ["laut lepas"], ["padang rumput"], ["rumput"], ["nektar"], ["tepi danau"], ["acara seminar itu"], ["universitas"], ["kuliah"], ["pantai"], ["pemimpin proyek"], ["warung kopi"], ["pakar bidang ekologi"], ["lomba menyanyi"], ["pembicara"], ["seminar"], ["tetangga"], ["pantainya"], ["pemandangan alam"], ["danau terdalam"], ["dunia"], ["ikon kota rio de janeiro"], ["kulinernya"], ["kota hujan"], ["tengah jakarta"], ["budaya indah"], ["malam hari"], ["jawa timur"], ["tahun baru saka"], ["negara penghasil minyak"], ["di dunia"], ["negara kepulauan"], ["rak sepatu"], ["tahap kontruksi"], ["taman belakang rumah"], ["perpustakaan"], ["acara tersebut"], ["setiap pagi"], ["mainan anak-anak"], ["buku"], ["rokok"], ["sejarah kebudayaan bali"], ["bahasa jepang"], ["pemain sepak bola"], ["orang medan"], ["kursi rotan"], ["dua orang"], ["boneka barunya"], ["sejarah panjang"], ["taman kita"], ["anak-anak"], ["pikiran"], ["orang tua"], ["kelemahannya"], ["kesejukan"], ["suasana romantis"], ["pendorong kesuksesan"], ["peliharaan manis"], ["karya seni kontemporer"], ["wisata daerah itu"], ["keluarga kami"], ["digunakan"], 
          ["NP", "Prep"], ["NumP", "NP"], ["NP", "Pronoun"], ["NP", "NumP"]],
    "VP" :[["Adj", "Verb"], ["VP", "Verb"], 
           ["mengambil"], ["menghadiri"], ["mengikuti"], ["diperbolehkan"], ["menaiki"], ["mempunyai"], ["menyelamatkan"], ["bermain"], ["memasak"], ["belajar"], ["menjaga"], ["terbang"], ["berenang"], ["berlari"], ["bergelantungan"], ["melompat-lompat"], ["hinggap"], ["mengunyah"], ["mengumpulkan"], ["sedang"], ["berjemur"], ["hadir"], ["memberikan"], ["adalah"], ["merupakan"], ["menjadi"], ["akan"], ["membantu"], ["terkenal dengan"], ["dikenal dengan"], ["terletak"], ["memiliki"], ["merupakan"], ["terpajang"], ["dalam tahap kontruksi"], ["belajar"], ["hadir"], ["nyaman"], ["indah"], ["sudah"], ["disiram"], ["berisi"], ["berlari"], ["membeli"], ["meneliti"], ["kursus"], ["orang medan"], ["menyukai"], ["dua orang"], ["disusun"], ["berlangsung"], ["senang"], ["indah"], ["menghibur"], ["membuat"], ["hewan peliharaan manis"], ["menampilkan"]],
    "PP" : [["Gagas"], ["Alaya"], ["Dr. Siti Rahayu"], ["Ani"], ["Adi Santoso"], ["Bu Ratna"], ["Prof. Dr. Hadi Prayitno"], ["Kiki"], ["Ibu Sinta"], ["Bapak Haryono"], 
          ["dia"], ["saya"], ["kita"], 
          ["nenek"], ["orang"], ["mahasiswa"], ["orang dewasa saja"], ["pemadam kebakaran"], ["anak laki-laki"], ["ibu"], ["siswa"], ["polisi"], ["burung"], ["ikan koi"], ["kuda pacuan"], ["monyet kecil"], ["kelinci putih"], ["lumba-lumba itu"], ["kupu-kupu"], ["sapi"], ["lebah"], ["buaya"], ["mahasiswa"], ["laut mediterania"], ["bukit tinggi"], ["danau baikal"], ["pantai copacabana"], ["bali"], ["kota bandung"], ["bogor"], ["monas"], ["denpasar"], ["surabaya"], ["pentas ogoh-ogoh"], ["arab saudi"], ["sepatu"], ["rumah"], ["kucing"], ["pengunjung"], ["siswa"], ["kamar tidur"], ["pertunjukan teater"], ["mobil"], ["bunga"], ["kotak besar"], ["kuda hitam"], ["bapak"], ["teman saya"], ["asrama putri"], ["bapak guru"], ["kakek"], ["pelatih tari"], ["rencana pelajaran"], ["pengembangan teknologi"], ["gadis kecil"], ["air terjun"], ["pertunjukan seni"], ["rumah tua"], ["bunga yang mekar"], ["kucing hitam"], ["udara sejuk"], ["prestasi anak-anak"], ["rasa cokelat"], ["pohon rindang"], ["air hujan"], ["cita-cita tinggi"], ["pameran"], ["budaya lokal"], ["hewan peliharaan"] ,["daun ubi"], ["sedikit waktu untuk"], ["ketertiban"], ["kebun"], ["acara"], ["kegiatan pengabdian"], ["wahana"], ["penduduk desa"], ["taman kota"], ["makanan lezat"], ["perpustakaan kampus"], ["jalan"], ["siang hari"], ["kolam taman"], ["lintasan pacu"], ["ranting pohon"], ["kebun"], ["laut lepas"], ["padang rumput"], ["rumput"], ["nektar"], ["tepi danau"], ["acara seminar itu"], ["universitas"], ["kuliah"], ["pantai"], ["pemimpin proyek"], ["warung kopi"], ["pakar bidang ekologi"], ["lomba menyanyi"], ["pembicara"], ["seminar"], ["tetangga"], ["pantainya"], ["pemandangan alam"], ["danau terdalam"], ["dunia"], ["ikon kota rio de janeiro"], ["kulinernya"], ["kota hujan"], ["tengah jakarta"], ["budaya indah"], ["malam hari"], ["jawa timur"], ["tahun baru saka"], ["negara penghasil minyak"], ["di dunia"], ["negara kepulauan"], ["rak sepatu"], ["tahap kontruksi"], ["taman belakang rumah"], ["perpustakaan"], ["acara tersebut"], ["setiap pagi"], ["mainan anak-anak"], ["buku"], ["rokok"], ["sejarah kebudayaan bali"], ["bahasa jepang"], ["pemain sepak bola"], ["orang medan"], ["kursi rotan"], ["dua orang"], ["boneka barunya"], ["sejarah panjang"], ["taman kita"], ["anak-anak"], ["pikiran"], ["orang tua"], ["kelemahannya"], ["kesejukan"], ["suasana romantis"], ["pendorong kesuksesan"], ["peliharaan manis"], ["karya seni kontemporer"], ["wisata daerah itu"], ["keluarga kami"], ["digunakan"], 
          ["NP", "Prep"], ["NumP", "NP"], ["NP", "Pronoun"], ["NP", "NumP"],
          ["Prep", "NP"], ["Prep", "VP"], ["Prep", "PP"], ["AdjP", "NP"], ["AdvP", "NP"]],
    "NumP" : [["para"], ["seekor"], ["banyak"], ["sekitar lima"], ["lima belas pasang"], ["delapan buah"], ["dua ekor"], ["sepuluh orang"], ["tujuh puluh lima orang"], ["tiga bungkus"], ["tiga buah"], ["sedikit"]],
    "AdjP" : [["keindahan"], ["terbesar"], ["kebanggaan"], ["teman setia"], ["kesegaran"], ["data tarik"], ["jarang"], ["banyak"], ["hanya"], ["selalu"], ["sering"], ["sedang"], ["sangat"], ["lama"], ["harus"]],
    "AdvP" : [["sekarang"], ["kemarin"], ["besok"]],

    "PropNoun" : [["Gagas"], ["Alaya"], ["Dr. Siti Rahayu"], ["Ani"], ["Adi Santoso"], ["Bu Ratna"], ["Prof. Dr. Hadi Prayitno"], ["Kiki"], ["Ibu Sinta"], ["Bapak Haryono"]],

    "Noun" : [["nenek"], ["orang"], ["mahasiswa"], ["orang dewasa saja"], ["pemadam kebakaran"], ["anak laki-laki"], ["ibu"], ["siswa"], ["polisi"], ["burung"], ["ikan koi"], ["kuda pacuan"], ["monyet kecil"], ["kelinci putih"], ["lumba-lumba itu"], ["kupu-kupu"], ["sapi"], ["lebah"], ["buaya"], ["mahasiswa"], ["laut mediterania"], ["bukit tinggi"], ["danau baikal"], ["pantai copacabana"], ["bali"], ["kota bandung"], ["bogor"], ["monas"], ["denpasar"], ["surabaya"], ["pentas ogoh-ogoh"], ["arab saudi"], ["sepatu"], ["rumah"], ["kucing"], ["pengunjung"], ["siswa"], ["kamar tidur"], ["pertunjukan teater"], ["mobil"], ["bunga"], ["kotak besar"], ["kuda hitam"], ["bapak"], ["teman saya"], ["asrama putri"], ["bapak guru"], ["kakek"], ["pelatih tari"], ["rencana pelajaran"], ["pengembangan teknologi"], ["gadis kecil"], ["air terjun"], ["pertunjukan seni"], ["rumah tua"], ["bunga yang mekar"], ["kucing hitam"], ["udara sejuk"], ["prestasi anak-anak"], ["rasa cokelat"], ["pohon rindang"], ["air hujan"], ["cita-cita tinggi"], ["pameran"], ["budaya lokal"], ["hewan peliharaan"] ,["daun ubi"], ["sedikit waktu untuk"], ["ketertiban"], ["kebun"], ["acara"], ["kegiatan pengabdian"], ["wahana"], ["penduduk desa"], ["taman kota"], ["makanan lezat"], ["perpustakaan kampus"], ["jalan"], ["siang hari"], ["kolam taman"], ["lintasan pacu"], ["ranting pohon"], ["kebun"], ["laut lepas"], ["padang rumput"], ["rumput"], ["nektar"], ["tepi danau"], ["acara seminar itu"], ["universitas"], ["kuliah"], ["pantai"], ["pemimpin proyek"], ["warung kopi"], ["pakar bidang ekologi"], ["lomba menyanyi"], ["pembicara"], ["seminar"], ["tetangga"], ["pantainya"], ["pemandangan alam"], ["danau terdalam"], ["dunia"], ["ikon kota rio de janeiro"], ["kulinernya"], ["kota hujan"], ["tengah jakarta"], ["budaya indah"], ["malam hari"], ["jawa timur"], ["tahun baru saka"], ["negara penghasil minyak"], ["di dunia"], ["negara kepulauan"], ["rak sepatu"], ["tahap kontruksi"], ["taman belakang rumah"], ["perpustakaan"], ["acara tersebut"], ["setiap pagi"], ["mainan anak-anak"], ["buku"], ["rokok"], ["sejarah kebudayaan bali"], ["bahasa jepang"], ["pemain sepak bola"], ["orang medan"], ["kursi rotan"], ["dua orang"], ["boneka barunya"], ["sejarah panjang"], ["taman kita"], ["anak-anak"], ["pikiran"], ["orang tua"], ["kelemahannya"], ["kesejukan"], ["suasana romantis"], ["pendorong kesuksesan"], ["peliharaan manis"], ["karya seni kontemporer"], ["wisata daerah itu"], ["keluarga kami"], ["digunakan"]],

    "Pronoun" : [["dia"], ["saya"], ["kita"]],

    "Verb" : [["mengambil"], ["menghadiri"], ["mengikuti"], ["diperbolehkan"], ["menaiki"], ["mempunyai"], ["menyelamatkan"], ["bermain"], ["memasak"], ["belajar"], ["menjaga"], ["terbang"], ["berenang"], ["berlari"], ["bergelantungan"], ["melompat-lompat"], ["hinggap"], ["mengunyah"], ["mengumpulkan"], ["sedang"], ["berjemur"], ["hadir"], ["memberikan"], ["adalah"], ["merupakan"], ["menjadi"], ["akan"], ["membantu"], ["terkenal dengan"], ["dikenal dengan"], ["terletak"], ["memiliki"], ["merupakan"], ["terpajang"], ["dalam tahap kontruksi"], ["belajar"], ["hadir"], ["nyaman"], ["indah"], ["sudah"], ["disiram"], ["berisi"], ["berlari"], ["membeli"], ["meneliti"], ["kursus"], ["orang medan"], ["menyukai"], ["dua orang"], ["disusun"], ["berlangsung"], ["senang"], ["indah"], ["menghibur"], ["membuat"], ["hewan peliharaan manis"], ["menampilkan"]],

    "Adv" : [["sekarang"], ["kemarin"], ["besok"]],

    "Adj" : [["keindahan"], ["terbesar"], ["kebanggaan"], ["teman setia"], ["kesegaran"], ["data tarik"], ["jarang"], ["banyak"], ["hanya"], ["selalu"], ["sering"], ["sedang"], ["sangat"], ["lama"], ["harus"]],

    "Prep" : [["itu"], ["ini"], ["tersebut"], ["di"], ["pada"], ["dalam"], ["di tengah"], ["dengan"]],

    "Num" : [["para"], ["seekor"], ["banyak"], ["sekitar lima"], ["lima belas pasang"], ["delapan buah"], ["dua ekor"], ["sepuluh orang"], ["tujuh puluh lima orang"], ["tiga bungkus"], ["tiga buah"], ["sedikit"]],

}


def cykParse(words):
    n = len(words)
    T = [[set([]) for _ in range(n)] for _ in range(n)]

    for j in range(n):
        for lhs, rule in R.items():
            for rhs in rule:
                if len(rhs) == 1 and rhs[0] == words[j]:
                    T[j][j].add(lhs)

        for i in range(j - 1, -1, -1):
            for k in range(i, j):
                for lhs, rule in R.items():
                    for rhs in rule:
                        if len(rhs) == 2 and rhs[0] in T[i][k] and rhs[1] in T[k + 1][j]:
                            T[i][j].add(lhs)

    if "K" in T[0][n - 1]:
        return ":green[Kalimat Anda Benar.]"
    else:
        return ":red[Kalimat Anda Salah.]"

def run_cyk(input_sentence):
    words = input_sentence.split()
    return cykParse(words)

def main():
    st.title("APAKAH :red[KALIMAT] ANDA BENAR ?")
    st.title("CEK :red[KALIMAT] ANDA DISINI")
    input_sentence = st.text_input(":green[ Contoh : Gagas makan Komodo kemarin]", placeholder="Masukan Kalimat Disini")

    if st.button("Lihat Hasil"):
        if input_sentence:
            st.write(f"Kalimat yang di cek : '{input_sentence}'")
            result = run_cyk(input_sentence)
            st.write(f"Hasilnya: {result}")
        else:
            st.write("Masukan Kalimat Terlebih Dahulu.")

if __name__ == "__main__":
    main()
